title: Tlaquepaque
description: Arts & Shopping Village
url: "https://tlaq.ab.team"
baseurl: ""
email: "katatsu12@gmail.com"
cdn_url: "https://tlaq.ab.team"

collections:
  blogs:
    output: true
    permalink: /news/:slug/
  landing:
    output: false
  shops:
    output: true
    permalink: /shops/:slug/
  galleries:
    output: true
    permalink: /galleries/:slug/
  foods:
    output: true
    permalink: /foods/:slug/
  events:
    output: true
    permalink: /events/:slug/
  articles:
    output: true
    permalink: /articles/:slug/
  weddings:
    output: true
    permalink: /weddings/:slug/
  wedding-articles:
    output: true

defaults:
  - scope:
      path: ""
      type: "shops"
    values:
      layout: "store/show"
      layout_type: "shop"
  - scope:
      path: ""
      type: "galleries"
    values:
      layout: "store/show"
      layout_type: "gallery"
  - scope:
      path: ""
      type: "foods"
    values:
      layout: "store/show"
      layout_type: "food"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "events/show"
      layout_type: "event"
  - scope:
      path: ""
      type: "blogs"
    values:
      layout: "blog/show"
      layout_type: "blog"
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "articles/show"
      layout_type: "article"
  - scope:
      path: ""
      type: "wedding-articles"
    values:
      layout: "articles/show"
      layout_type: "article"
  - scope:
      path: ""
      type: "weddings"
    values:
      layout: "weddings/show"
      layout_type: "wedding"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 8
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true

include:
  - .well-known

exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - vendor/
